# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Need to give some name to blog
email: v i i s h a a l@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog about random Data Science experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://viishaal.github.io" # the base hostname & protocol for your site
twitter_username: junejavishu
github_username:  viishaal

# Build settings
markdown: kramdown
